language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
sudo: false
install:
  - pip install folium
  - pip install coveralls
script: nosetests tests --verbose --with-coverage
after_success:
  - coveralls
notifications:
  email: false